/**
 * @file herkulex_keywords.h
 */
//
// Created by Ksyy on 04/12/16.
//

/**
 * This file define a lots of useful macro for creating or reading Herkulex messages
 */

#ifndef HERKULEX_KEYWORDS_H
#define HERKULEX_KEYWORDS_H

#define HKL_MAX_MSG_SIZE 223

#define HKL_HEADER 0xFF  // Header of message, send 2 times

#define HKL_CHECKSUM 0xFE // Value to AND with the checksums


// Commands
#define HKL_EEP_WRITE 0x01
#define HKL_EEP_READ 0x02
#define HKL_RAM_WRITE 0x03
#define HKL_RAM_READ 0x04
#define HKL_I_JOG 0x05  // Commands multiple servos, each with a time of motion
#define HKL_S_JOG 0x06 // Commands multiple servos, same time of motion
#define HKL_STAT 0x07
#define HKL_ROLLBACK 0x08
#define HKL_REBOOT 0x09

// ACK Commands
#define HKL_ACK_EEP_WRITE 0x01
#define HKL_ACK_EEP_READ 0x02
#define HKL_ACK_RAM_WRITE 0x03
#define HKL_ACK_RAM_READ 0x04
#define HKL_ACK_I_JOG 0x05
#define HKL_ACK_S_JOG 0x06
#define HKL_ACK_STAT 0x07
#define HKL_ACK_ROLLBACK 0x08
#define HKL_ACK_REBOOT 0x09

// Addresses Non-Volatile Register
#define HKL_REG_MODEL_NB_1 0x00  // LSB
#define HKL_REG_MODEL_NB_2 0x01  // MSB
#define HKL_REG_FIRMWARE_VERSION_1 0x02 // LSB
#define HKL_REG_FIRMWARE_VERSION_2 0x03 // MSB
#define HKL_REG_BAUD_RATE 0x04
#define HKL_REG_ID 0x06
#define HKL_REG_ACK_POLICY 0x07
#define HKL_REG_ALARM_LED_POLICY 0x08
#define HKL_REG_TORQUE_POLICY 0x09
#define HKL_REG_MAX_TEMP_ALLOWED 0x0B
#define HKL_REG_MIN_VOLTAGE_ALLOWED 0x0C
#define HKL_REG_MAX_VOLTAGE_ALLOWED 0x0D
#define HKL_REG_ACCELERATION_RATIO 0x0E
#define HKL_REG_MAX_ACCELERATION_TIME 0x0F
#define HKL_REG_DEAD_ZONE 0x10
#define HKL_REG_SATURATOR_OFFSET 0x11
#define HKL_REG_SATURATOR_SLOPE 0x12 // 2 Bytes
#define HKL_REG_PWM_OFFSET 0x14
#define HKL_REG_MIN_PWM_VALUE 0x15
#define HKL_REG_MAX_PWM_VALUE 0x16 // 2 Bytes
#define HKL_REG_PWM_OVERLOAD_THRESHOLD 0x18 // 2 Bytes
#define HKL_REG_MIN_POSITION_VALUE 0x1A // 2 Bytes
#define HKL_REG_MAX_POSITION_VALUE 0x1C // 2 Bytes
#define HKL_REG_KP 0x1E // 2 Bytes
#define HKL_REG_KD 0x20 // 2 Bytes
#define HKL_REG_KI 0x22 // 2 Bytes
#define HKL_REG_FEEDFORWARD_1 0x24 // 2 Bytes
#define HKL_REG_FEEDFORWARD_2 0x26 // 2 Bytes
#define HKL_REG_LED_BLINK_PERIOD 0x2C
#define HKL_REG_ADC_FAULT_CHECK_PERIOD 0x2D
#define HKL_REG_PACKET_GARBAGE_CHECK_PERIOD 0x2E
#define HKL_REG_STOP_DETECTION_CHECK_PERIOD 0x2F
#define HKL_REG_OVERLOAD_DETECTION_PERIOD 0x30
#define HKL_REG_STOP_THRESHOLD 0x31
#define HKL_REG_IN_POSITION_MARGIN 0x32
#define HKL_REG_CALIBRATION_DIFFERENCE 0x35

// Addresses Volatile Register (RAM)
#define HKL_RAM_ID 0x00
#define HKL_RAM_ACK_POLICY 0x01
#define HKL_RAM_ALARM_LED_POLICY 0x02
#define HKL_RAM_TORQUE_POLICY 0x03
#define HKL_RAM_MAX_TEMP_ALLOWED 0x05
#define HKL_RAM_MIN_VOLTAGE_ALLOWED 0x06
#define HKL_RAM_MAX_VOLTAGE_ALLOWED 0x07
#define HKL_RAM_ACCELERATION_RATIO 0x08
#define HKL_RAM_MAX_ACCELERATION_TIME 0x09
#define HKL_RAM_DEAD_ZONE 0x0A
#define HKL_RAM_SATURATOR_OFFSET 0x0B
#define HKL_RAM_SATURATOR_SLOPE 0x0C // 2 Bytes
#define HKL_RAM_PWM_OFFSET 0x0E
#define HKL_RAM_MIN_PWM_VALUE 0x0F
#define HKL_RAM_MAX_PWM_VALUE 0x10 // 2 Bytes
#define HKL_RAM_PWM_OVERLOAD_THRESHOLD 0x12 // 2 Bytes
#define HKL_RAM_MIN_POSITION_VALUE 0x14 // 2 Bytes
#define HKL_RAM_MAX_POSITION_VALUE 0x16 // 2 Bytes
#define HKL_RAM_KP 0x18 // 2 Bytes
#define HKL_RAM_KD 0x1A // 2 Bytes
#define HKL_RAM_KI 0x1C // 2 Bytes
#define HKL_RAM_FEEDFORWARD_1 0x1E // 2 Bytes
#define HKL_RAM_FEEDFORWARD_2 0x20 // 2 Bytes
#define HKL_RAM_LED_BLINK_PERIOD 0x26
#define HKL_RAM_ADC_FAULT_CHECK_PERIOD 0x27
#define HKL_RAM_PACKET_GARBAGE_CHECK_PERIOD 0x28
#define HKL_RAM_STOP_DETECTION_CHECK_PERIOD 0x29
#define HKL_RAM_OVERLOAD_DETECTION_PERIOD 0x2A
#define HKL_RAM_STOP_THRESHOLD 0x2B
#define HKL_RAM_IN_POSITION_MARGIN 0x2C
#define HKL_RAM_CALIBRATION_DIFFERENCE 0x2F
#define HKL_RAM_STATUS_ERROR 0x30
#define HKL_RAM_STATUS_DETAIL 0x31
#define HKL_RAM_TORQUE_CONTROL 0x34
#define HKL_RAM_LED_CONTROL 0x35
#define HKL_RAM_VOLTAGE 0x36
#define HKL_RAM_TEMPERATURE 0x37
#define HKL_RAM_CURRENT_MODE_CONTROL 0x38
#define HKL_RAM_TICK 0x39
#define HKL_RAM_CALIBRATED_POSITION 0x3A
#define HKL_RAM_ABSOLUTE_POSITION 0x3C
#define HKL_RAM_DIFFERENTIAL_POSITION 0x3E
#define HKL_RAM_PWM 0x40
#define HKL_RAM_ABSOLUTION_GOAL_POSITION 0x44
#define HKL_RAM_ABSOLUTION_DESIRED_TRAJECTORY_POSITION 0x46
#define HKL_RAM_DESIRED_VELOCITY 0x48


#endif //HERKULEX_KEYWORDS_H
